# Generated by Django 5.0 on 2024-08-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록시각'),
        ),
    ]
