# Generated by Django 5.0 on 2024-09-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0006_alter_tag_high_alter_tag_vid_alter_usertoken_useable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='high',
            name='url',
        ),
        migrations.AddField(
            model_name='high',
            name='timestamp',
            field=models.IntegerField(default=None, verbose_name='timestamp'),
        ),
    ]
